//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcsc.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcsc.Properties.Langs.Lang_en", typeof(Lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the server &quot;brain&quot;!.
        /// </summary>
        internal static string agy {
            get {
                return ResourceManager.GetString("agy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have already found server with this name! Enter another name!.
        /// </summary>
        internal static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (We working on another brains).
        /// </summary>
        internal static string another_agy {
            get {
                return ResourceManager.GetString("another_agy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bukkit is not avaliable yet!.
        /// </summary>
        internal static string bukkit_not_avaliable {
            get {
                return ResourceManager.GetString("bukkit_not_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (If you don&apos;t see the new version, the minecraft server creator is not compatible with this version yet!).
        /// </summary>
        internal static string dont_see {
            get {
                return ResourceManager.GetString("dont_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the server name!.
        /// </summary>
        internal static string enter_srv_name {
            get {
                return ResourceManager.GetString("enter_srv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get started.
        /// </summary>
        internal static string f_bele {
            get {
                return ResourceManager.GetString("f_bele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all fields!.
        /// </summary>
        internal static string fill_all_fields {
            get {
                return ResourceManager.GetString("fill_all_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should be the name of the server?.
        /// </summary>
        internal static string s_name {
            get {
                return ResourceManager.GetString("s_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select it!.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please enter the name without special characters).
        /// </summary>
        internal static string spec_car {
            get {
                return ResourceManager.GetString("spec_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string tovabb {
            get {
                return ResourceManager.GetString("tovabb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Minecraft Server Creator!
        ///We have questions to create your own server!
        ///If you don&apos;t know what is the best, you can click the question mark!.
        /// </summary>
        internal static string udv {
            get {
                return ResourceManager.GetString("udv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version!.
        /// </summary>
        internal static string what_version {
            get {
                return ResourceManager.GetString("what_version", resourceCulture);
            }
        }
    }
}
