//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcsc.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_hu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_hu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcsc.Properties.Langs.Lang_hu", typeof(Lang_hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok lekérdezése.
        /// </summary>
        internal static string adat_lekerd {
            get {
                return ResourceManager.GetString("adat_lekerd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi legyen a szervernek az &quot;agya&quot;?.
        /// </summary>
        internal static string agy {
            get {
                return ResourceManager.GetString("agy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az úgynevezett &quot;agy&quot;, a szerver egyik legfontosabb alkotóeleme.
        ///
        ///Ebből itt te kettő félét találsz. A Spigotot és a Bukkitot.
        ///
        ///Ezek között a legfőbb különbség, hogy a Spigot tudja futtatni a 
        ///bukkitos kiegészítőket is, viszont a Bukkit nem. 
        ///
        ///Ennek ellenére még sokan vannak akik  bukkitot használnak. 
        ///
        ///Hogyha esetleg egy olyan szervert szeretnél, ahol több féle
        /// játékmód van, azaz több szerver fut egyszerre akkor ez csak a Spigot-al
        ///oldható meg ebben az alkalmazásban. Ez a funkció majd az 1.6-s ve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agy_form {
            get {
                return ResourceManager.GetString("agy_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilyen nevű szerver már létezik! Adj meg egy másik nevet!.
        /// </summary>
        internal static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Az egyéb agyakon még dolgozunk!).
        /// </summary>
        internal static string another_agy {
            get {
                return ResourceManager.GetString("another_agy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bukkit még nem elérhető!.
        /// </summary>
        internal static string bukkit_not_avaliable {
            get {
                return ResourceManager.GetString("bukkit_not_avaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Ha valamilyen verziót nem látsz, akkor abban a verzióban még nem lehetséges szervert készíteni).
        /// </summary>
        internal static string dont_see {
            get {
                return ResourceManager.GetString("dont_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Írd be a szervered nevét!.
        /// </summary>
        internal static string enter_srv_name {
            get {
                return ResourceManager.GetString("enter_srv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fogjunk bele!.
        /// </summary>
        internal static string f_bele {
            get {
                return ResourceManager.GetString("f_bele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Töltsd ki az összes mezőt!.
        /// </summary>
        internal static string fill_all_fields {
            get {
                return ResourceManager.GetString("fill_all_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem ajánlott verziók: 1.16.1.
        /// </summary>
        internal static string not_recommented_versions {
            get {
                return ResourceManager.GetString("not_recommented_versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Játékosok.
        /// </summary>
        internal static string players {
            get {
                return ResourceManager.GetString("players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pluginok.
        /// </summary>
        internal static string plugins {
            get {
                return ResourceManager.GetString("plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajánlott beállítások:.
        /// </summary>
        internal static string rec_settings {
            get {
                return ResourceManager.GetString("rec_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajánlott verziók: 1.14.4
        ///                          1.14.3
        ///                          1.14.2
        ///                          1.14
        ///                          1.12.2
        ///                          1.12.
        /// </summary>
        internal static string recommented_versions {
            get {
                return ResourceManager.GetString("recommented_versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi legyen a szerver neve?.
        /// </summary>
        internal static string s_name {
            get {
                return ResourceManager.GetString("s_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válaszd ki!.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Lehetőleg speciális karakterek nélküli nevet adj meg).
        /// </summary>
        internal static string spec_car {
            get {
                return ResourceManager.GetString("spec_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovább.
        /// </summary>
        internal static string tovabb {
            get {
                return ResourceManager.GetString("tovabb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöllek a minecraft szerver készítőben! 
        ///A szerver elkészítéséhez a telepítő fel fog tenni
        ///kérdéseket. Ha valamelyik kérdésre esetleg
        ///nem tudod a választ, akkor kattints a
        ///kérdés melletti kérdőjelre.
        /// </summary>
        internal static string udv {
            get {
                return ResourceManager.GetString("udv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.12 alattiak.
        /// </summary>
        internal static string under {
            get {
                return ResourceManager.GetString("under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Válassz egy olyan verziót ami nem túl régi, de nem is nagyon új. 
        ///Ha nagyon újat választasz, sok kiegészítő (un. plugin) nem lesz elérhető. 
        ///Viszont ez a veszély akkor is előáll, ha nagyon régit választasz..
        /// </summary>
        internal static string verzio_form {
            get {
                return ResourceManager.GetString("verzio_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milyen verzióban szeretnél játszani?.
        /// </summary>
        internal static string what_version {
            get {
                return ResourceManager.GetString("what_version", resourceCulture);
            }
        }
    }
}
