//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcsc.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_hu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_hu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mcsc.Properties.Langs.Lang_hu", typeof(Lang_hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilyen nevű szerver már létezik! Adj meg egy másik nevet!.
        /// </summary>
        internal static string already {
            get {
                return ResourceManager.GetString("already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Írd be a szervered nevét!.
        /// </summary>
        internal static string enter_srv_name {
            get {
                return ResourceManager.GetString("enter_srv_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fogjunk bele!.
        /// </summary>
        internal static string f_bele {
            get {
                return ResourceManager.GetString("f_bele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi legyen a szerver neve?.
        /// </summary>
        internal static string s_name {
            get {
                return ResourceManager.GetString("s_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Lehetőleg speciális karakterek nélküli nevet adj meg).
        /// </summary>
        internal static string spec_car {
            get {
                return ResourceManager.GetString("spec_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tovább.
        /// </summary>
        internal static string tovabb {
            get {
                return ResourceManager.GetString("tovabb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöllek a minecraft szerver készítőben! 
        ///A szerver elkészítéséhez a telepítő fel fog tenni
        ///kérdéseket. Ha valamelyik kérdésre esetleg
        ///nem tudod a választ, akkor kattints a
        ///kérdés melletti kérdőjelre.
        /// </summary>
        internal static string udv {
            get {
                return ResourceManager.GetString("udv", resourceCulture);
            }
        }
    }
}
